'use strict';

const products = [
    { id: 'ssd', name: 'SSD 1TB', description: 'NVMe PCIe Gen4 SSD', price: 2790, image: 'ssd.webp', specs: { Capacity: '1TB', 'Form Factor': 'M.2 2280', Interface: 'PCIe Gen 4.0' } },
    { id: 'mouse', name: 'Gaming Mouse', description: 'High Precision RGB Gaming Mouse', price: 890, image: 'Mouse.jpg', specs: { Sensor: 'High-Precision Optical Sensor', DPI: 'Adjustable' } },
    { id: 'keyboard', name: 'Mechanical Keyboard', description: 'RGB Mechanical Keyboard Blue Switch', price: 1590, image: 'keyboard.jpg', specs: { 'Switch Type': 'Outemu Blue Switch', Connection: 'USB' } },
    { id: 'headset', name: 'Gaming Headset', description: '7.1 Surround Sound Headset', price: 1290, image: 'Gaming headset.jpg', specs: { Audio: 'Virtual 7.1 Surround Sound', Drivers: '50mm' } },
    { id: 'monitor', name: 'Gaming Monitor', description: '24-inch Full HD 180Hz Monitor', price: 5990, image: 'monitor1.webp', specs: { Size: '24 นิ้ว', Resolution: 'Full HD', Refresh: '180Hz' } },
    { id: 'laptop', name: 'Gaming Laptop', description: '15.6-inch Gaming Laptop', price: 35900, image: 'laptop.webp', specs: { CPU: 'Intel Core i5-13500H', GPU: 'RTX 4050' } },
    { id: 'chair', name: 'Gaming Chair', description: 'Ergonomic Gaming Chair', price: 4990, image: 'chair.webp', specs: { Material: 'Premium PU Leather', Recline: '160 องศา' } },
    { id: 'rtx', name: 'Graphics Card RTX 4070', description: 'High Performance Graphics Card', price: 22990, image: 'rtx.webp', specs: { Chipset: 'NVIDIA GeForce RTX 4070', VRAM: '12GB' } },
    { id: 'intel', name: 'Intel Core i7 Processor', description: '13th Gen High Speed Processor', price: 11900, image: 'intel.webp', specs: { Model: 'Intel Core i7-13700F', Generation: '13th Gen' } },
    { id: 'ram', name: 'RAM 16GB DDR5', description: 'High Speed DDR5 Memory', price: 2490, image: 'ram.webp', specs: { Capacity: '16GB', Type: 'DDR5', Speed: '5200 MHz' } },
    { id: 'case', name: 'RGB PC Case', description: 'Tempered Glass Gaming Case', price: 2990, image: 'case.webp', specs: { Form: 'Mid-Tower', Panel: 'Tempered Glass' } }
];

let cart = loadCart();
function formatPrice(value) { return `${new Intl.NumberFormat('th-TH').format(value)} THB`; }
function loadCart() { try { const saved = JSON.parse(localStorage.getItem('techzone_cart') || '[]'); return Array.isArray(saved) ? saved : []; } catch { return []; } }
function saveCart() { localStorage.setItem('techzone_cart', JSON.stringify(cart)); }
function updateCartBadge() { document.querySelectorAll('#cartBadge').forEach((badge) => { badge.textContent = cart.reduce((total, item) => total + item.quantity, 0); }); }
function showToast(message) { const toast = document.getElementById('toast'); if (!toast) return; toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 2200); }
function addToCart(productId) { const product = products.find((item) => item.id === productId); if (!product) return; const existing = cart.find((item) => item.id === productId); if (existing) existing.quantity += 1; else cart.push({ id: product.id, name: product.name, price: product.price, image: product.image, quantity: 1 }); saveCart(); updateCartBadge(); renderCart(); showToast('เพิ่มสินค้าลงตะกร้าแล้ว'); }
function changeCartQuantity(productId, amount) { const item = cart.find((entry) => entry.id === productId); if (!item) return; item.quantity += amount; if (item.quantity <= 0) cart = cart.filter((entry) => entry.id !== productId); saveCart(); updateCartBadge(); renderCart(); }
function renderProductCard(product) { return `<article class="product-card"><img src="${product.image}" alt="${product.name}" loading="lazy"><div class="product-card-body"><h3>${product.name}</h3><p class="product-description">${product.description}</p><p class="product-specs"><strong>Specs:</strong> ${Object.entries(product.specs).slice(0, 3).map(([key, value]) => `${key}: ${value}`).join(' · ')}</p><p class="product-price">${formatPrice(product.price)}</p><div class="product-actions"><button class="button button-secondary" type="button" data-action="details" data-id="${product.id}">View Details</button><button class="button button-accent" type="button" data-action="add" data-id="${product.id}">Add to Cart</button></div></div></article>`; }
function renderFeaturedProducts() { const target = document.getElementById('featuredProducts'); if (target) target.innerHTML = products.slice(0, 4).map(renderProductCard).join(''); }
function renderProducts() { const grid = document.getElementById('productGrid'); if (!grid) return; const search = (document.getElementById('searchInput')?.value || '').trim().toLowerCase(); const sort = document.getElementById('sortSelect')?.value || 'default'; let result = products.filter((product) => `${product.name} ${product.description} ${Object.entries(product.specs).map(([key, value]) => `${key} ${value}`).join(' ')}`.toLowerCase().includes(search)); if (sort === 'price-low') result.sort((a, b) => a.price - b.price); if (sort === 'price-high') result.sort((a, b) => b.price - a.price); grid.innerHTML = result.length ? result.map(renderProductCard).join('') : '<div class="empty-state">ไม่พบสินค้าที่ตรงกับการค้นหา</div>'; const count = document.getElementById('productCount'); if (count) count.textContent = `พบสินค้า ${result.length} รายการ`; }
function showProductDetails(productId) { const product = products.find((item) => item.id === productId); if (!product) return; const modal = document.createElement('div'); modal.className = 'modal-backdrop'; modal.innerHTML = `<div class="modal" role="dialog" aria-modal="true" aria-label="รายละเอียดสินค้า"><button class="modal-close" type="button" aria-label="ปิด">×</button><img src="${product.image}" alt="${product.name}"><span class="eyebrow">PRODUCT DETAIL</span><h2>${product.name}</h2><p>${product.description}</p><div class="product-specifications"><h3>Technical Specifications</h3><ul class="spec-list">${Object.entries(product.specs).map(([key, value]) => `<li><strong>${key}:</strong> ${value}</li>`).join('')}</ul></div><p class="product-price">${formatPrice(product.price)}</p><button class="button button-accent" type="button" data-modal-add="${product.id}">Add to Cart</button></div>`; document.body.appendChild(modal); const close = () => modal.remove(); modal.querySelector('.modal-close').addEventListener('click', close); modal.addEventListener('click', (event) => { if (event.target === modal) close(); }); modal.querySelector('[data-modal-add]').addEventListener('click', () => { addToCart(product.id); close(); }); }
function renderCart() { const target = document.getElementById('cartItems'); const totalTarget = document.getElementById('cartTotal'); if (!target || !totalTarget) return; if (!cart.length) { target.innerHTML = '<div class="empty-state">ยังไม่มีสินค้าในตะกร้า</div>'; totalTarget.textContent = '0 THB'; return; } target.innerHTML = cart.map((item) => `<div class="cart-item"><img src="${item.image}" alt="${item.name}"><div><h3>${item.name}</h3><p>${formatPrice(item.price)} / ชิ้น</p></div><div class="quantity-controls"><button type="button" data-cart-action="minus" data-id="${item.id}">−</button><span>${item.quantity}</span><button type="button" data-cart-action="plus" data-id="${item.id}">+</button></div><strong>${formatPrice(item.price * item.quantity)}</strong></div>`).join(''); totalTarget.textContent = formatPrice(cart.reduce((sum, item) => sum + item.price * item.quantity, 0)); }
async function apiCall(endpoint, method = 'GET', data = null) { const options = { method, headers: { 'Content-Type': 'application/json' } }; if (data !== null) options.body = JSON.stringify(data); const response = await fetch(endpoint, options); let result = null; try { result = await response.json(); } catch { result = null; } if (!response.ok) { const error = new Error(result?.message || `Request failed with status ${response.status}`); error.status = response.status; error.data = result; throw error; } return result; }
function setupLogin() { const form = document.getElementById('loginForm'); if (!form) return; const button = document.getElementById('loginButton'); const errorBox = document.getElementById('loginError'); form.addEventListener('submit', async (event) => { event.preventDefault(); errorBox.style.display = 'none'; const userEmail = document.getElementById('email').value.trim(); const userPassword = document.getElementById('password').value; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(userEmail)) { errorBox.textContent = 'กรุณากรอกอีเมลให้ถูกต้อง'; errorBox.style.display = 'block'; return; } if (!userPassword) { errorBox.textContent = 'กรุณากรอกรหัสผ่าน'; errorBox.style.display = 'block'; return; } button.disabled = true; button.textContent = 'Loading...'; try { const data = await apiCall(form.action, 'POST', { email: userEmail, password: userPassword }); if (data?.token) localStorage.setItem('token', data.token); window.location.href = 'index.html'; } catch (error) { errorBox.textContent = error.status === 401 ? (error.data?.message || 'อีเมลหรือรหัสผ่านไม่ถูกต้อง') : 'ยังไม่สามารถเข้าสู่ระบบได้'; errorBox.style.display = 'block'; document.getElementById('password').value = ''; button.disabled = false; button.textContent = 'Login'; } }); }
document.addEventListener('click', (event) => { const actionButton = event.target.closest('[data-action]'); if (actionButton) { const { action, id } = actionButton.dataset; if (action === 'add') addToCart(id); if (action === 'details') showProductDetails(id); } const cartButton = event.target.closest('[data-cart-action]'); if (cartButton) changeCartQuantity(cartButton.dataset.id, cartButton.dataset.cartAction === 'plus' ? 1 : -1); });
document.addEventListener('DOMContentLoaded', () => { updateCartBadge(); renderFeaturedProducts(); renderProducts(); renderCart(); setupLogin(); document.getElementById('searchInput')?.addEventListener('input', renderProducts); document.getElementById('sortSelect')?.addEventListener('change', renderProducts); document.getElementById('checkoutButton')?.addEventListener('click', () => showToast(cart.length ? 'ระบบสั่งซื้อจะเชื่อม Backend ใน Phase 2' : 'กรุณาเพิ่มสินค้าก่อนสั่งซื้อ')); });
