'use strict';

const products = [
  { id:'ssd', name:'SSD 1TB', description:'NVMe PCIe Gen4 SSD', price:2790, image:'ssd.webp', specs:{Capacity:'1TB', Interface:'PCIe Gen 4.0'} },
  { id:'mouse', name:'Gaming Mouse', description:'High Precision RGB Gaming Mouse', price:890, image:'Mouse.jpg', specs:{Sensor:'High Precision', DPI:'Adjustable'} },
  { id:'keyboard', name:'Mechanical Keyboard', description:'RGB Mechanical Keyboard Blue Switch', price:1590, image:'keyboard.jpg', specs:{Switch:'Blue Switch', Lighting:'RGB'} },
  { id:'headset', name:'Gaming Headset', description:'7.1 Surround Sound Headset', price:1290, image:'Gaming headset.jpg', specs:{Audio:'Virtual 7.1', Driver:'50mm'} },
  { id:'monitor', name:'Gaming Monitor', description:'24-inch Full HD 180Hz Monitor', price:5990, image:'monitor1.webp', specs:{Size:'24 inch', Refresh:'180Hz'} },
  { id:'laptop', name:'Gaming Laptop', description:'15.6-inch Gaming Laptop', price:35900, image:'laptop.webp', specs:{Display:'15.6 inch', GPU:'RTX 4050'} },
  { id:'chair', name:'Gaming Chair', description:'Ergonomic Gaming Chair', price:4990, image:'chair.webp', specs:{Material:'Premium PU Leather', Recline:'160 degrees'} },
  { id:'rtx', name:'Graphics Card RTX 4070', description:'High Performance Graphics Card', price:22990, image:'rtx.webp', specs:{VRAM:'12GB', Interface:'PCIe'} },
  { id:'intel', name:'Intel Core i7 Processor', description:'13th Gen High Speed Processor', price:11900, image:'intel.webp', specs:{Generation:'13th Gen', Socket:'LGA1700'} },
  { id:'ram', name:'RAM 16GB DDR5', description:'High Speed DDR5 Memory', price:2490, image:'ram.webp', specs:{Capacity:'16GB', Type:'DDR5'} },
  { id:'case', name:'RGB PC Case', description:'Tempered Glass Gaming Case', price:2990, image:'case.webp', specs:{Form:'Mid-Tower', Panel:'Tempered Glass'} }
];

const SUPABASE_URL = 'https://oofzpcisbhwdpmzzsxlm.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_6qyaccGoXnRDoUyRbGBJ9Q_oDCjC6jm';
const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
const money = value => `${new Intl.NumberFormat('th-TH').format(value)} THB`;

async function registerUser({name,email,password}) { const {data,error}=await supabaseClient.auth.signUp({email,password,options:{data:{name}}}); if(error) throw new Error(error.message); return data.user; }
async function loginUser(email,password) { const {data,error}=await supabaseClient.auth.signInWithPassword({email,password}); if(error) throw new Error(error.message); return data.user; }
async function currentUser() { const {data:{session}}=await supabaseClient.auth.getSession(); if(!session)return null; const {data,error}=await supabaseClient.from('profiles').select('id,name,email,wallet_balance').eq('id',session.user.id).single(); return error||!data?null:{id:data.id,name:data.name||session.user.email,email:data.email||session.user.email,wallet:Number(data.wallet_balance||0)}; }
async function orders() { const {data,error}=await supabaseClient.from('orders').select('id,items,total,created_at').order('created_at',{ascending:false}); return error?[]:data.map(o=>({...o, total:Number(o.total)})); }
async function checkout(items) { const {data,error}=await supabaseClient.rpc('checkout',{p_items:items.map(({id,quantity})=>({product_id:id,quantity}))}); if(error)throw new Error(error.message); return data; }

let cart=[];
try { cart=JSON.parse(localStorage.getItem('techzone_cart')||'[]'); if(!Array.isArray(cart))cart=[]; } catch { cart=[]; }
const save=()=>localStorage.setItem('techzone_cart',JSON.stringify(cart));
const toast=message=>{const el=document.getElementById('toast');if(!el)return;el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200);};
function badge(){document.querySelectorAll('#cartBadge').forEach(e=>e.textContent=cart.reduce((n,i)=>n+i.quantity,0));}
function card(p){return `<article class="product-card"><img src="${p.image}" alt="${p.name}" loading="lazy"><div class="product-card-body"><h3>${p.name}</h3><p class="product-description">${p.description}</p><p class="product-specs"><strong>Specs:</strong> ${Object.entries(p.specs).map(([k,v])=>`${k}: ${v}`).join(' · ')}</p><p class="product-price">${money(p.price)}</p><div class="product-actions"><button class="button button-secondary" data-action="details" data-id="${p.id}">View Details</button><button class="button button-accent" data-action="add" data-id="${p.id}">Add to Cart</button></div></div></article>`;}
function renderProducts(){const grid=document.getElementById('productGrid');if(!grid)return;const q=(document.getElementById('searchInput')?.value||'').toLowerCase();let list=products.filter(p=>(p.name+' '+p.description).toLowerCase().includes(q));const sort=document.getElementById('sortSelect')?.value;if(sort==='price-low')list.sort((a,b)=>a.price-b.price);if(sort==='price-high')list.sort((a,b)=>b.price-a.price);grid.innerHTML=list.map(card).join('');const count=document.getElementById('productCount');if(count)count.textContent=`พบสินค้า ${list.length} รายการ`;}
function renderCart(){const el=document.getElementById('cartItems'),total=document.getElementById('cartTotal');if(!el||!total)return;el.innerHTML=cart.length?cart.map(i=>`<div class="cart-item"><img src="${i.image}" alt="${i.name}"><div><h3>${i.name}</h3><p>${money(i.price)} / ชิ้น</p></div><div class="quantity-controls"><button data-cart-action="minus" data-id="${i.id}">−</button><span>${i.quantity}</span><button data-cart-action="plus" data-id="${i.id}">+</button></div><strong>${money(i.price*i.quantity)}</strong></div>`).join(''):'<div class="empty-state">ยังไม่มีสินค้าในตะกร้า</div>';total.textContent=money(cart.reduce((n,i)=>n+i.price*i.quantity,0));}
async function authArea(){const u=await currentUser();document.querySelectorAll('.auth-area').forEach(e=>e.innerHTML=u?`<a class="wallet-chip" href="account.html">👛 ${money(u.wallet)}</a><a class="login-link" href="account.html">👤 ${(u.name||'บัญชี').split(' ')[0]}</a><button class="logout-btn" data-action="logout">ออกจากระบบ</button>`:'<a class="login-link" href="login.html">♙ เข้าสู่ระบบ</a>');}
async function account(){const name=document.getElementById('accountName');if(!name)return;const u=await currentUser();if(!u){location.href='login.html';return;}name.textContent=u.name;document.getElementById('accountEmail').textContent=u.email;document.getElementById('walletBalance').textContent=money(u.wallet);const list=await orders();document.getElementById('orderHistory').innerHTML=list.length?list.map(o=>`<div class="order-item"><div class="order-item-head"><strong>คำสั่งซื้อ #${o.id.slice(0,8)}</strong><small>${new Date(o.created_at).toLocaleString('th-TH')}</small></div><p class="order-products">${(o.items||[]).map(i=>`${i.name||i.product_id} ×${i.quantity}`).join(', ')}</p><strong class="order-total">${money(o.total)}</strong></div>`).join(''):'<div class="empty-state">ยังไม่มีประวัติการสั่งซื้อ</div>';}
function add(id){const p=products.find(x=>x.id===id),i=cart.find(x=>x.id===id);if(!p)return;if(i)i.quantity++;else cart.push({...p,quantity:1});save();badge();renderCart();toast('เพิ่มสินค้าลงตะกร้าแล้ว');}

document.addEventListener('click',async e=>{const a=e.target.closest('[data-action]');if(a){if(a.dataset.action==='add')add(a.dataset.id);if(a.dataset.action==='logout'){await supabaseClient.auth.signOut();await authArea();toast('ออกจากระบบแล้ว');}if(a.dataset.action==='details'){const p=products.find(x=>x.id===a.dataset.id);alert(`${p.name}\n${p.description}\n${money(p.price)}`);}}const c=e.target.closest('[data-cart-action]');if(c){const i=cart.find(x=>x.id===c.dataset.id);if(i){i.quantity+=c.dataset.cartAction==='plus'?1:-1;if(i.quantity<=0)cart=cart.filter(x=>x.id!==i.id);save();badge();renderCart();}}});
document.addEventListener('DOMContentLoaded',()=>{badge();authArea();renderProducts();document.getElementById('featuredProducts')?.replaceChildren(...products.slice(0,4).map(p=>{const d=document.createElement('div');d.outerHTML=card(p);return d;}));renderCart();account();document.getElementById('searchInput')?.addEventListener('input',renderProducts);document.getElementById('sortSelect')?.addEventListener('change',renderProducts);document.getElementById('checkoutButton')?.addEventListener('click',async()=>{if(!cart.length)return toast('กรุณาเพิ่มสินค้าลงตะกร้าก่อน');if(!await currentUser()){location.href='login.html';return;}try{await checkout(cart);cart=[];save();badge();renderCart();await authArea();toast('สั่งซื้อสำเร็จ!');}catch(err){toast('สั่งซื้อไม่สำเร็จ: '+err.message);}});const lf=document.getElementById('loginForm');lf?.addEventListener('submit',async e=>{e.preventDefault();try{await loginUser(document.getElementById('email').value.trim(),document.getElementById('password').value);location.href='index.html';}catch(err){document.getElementById('loginError').textContent=err.message;document.getElementById('loginError').style.display='block';}});const rf=document.getElementById('registerForm');rf?.addEventListener('submit',async e=>{e.preventDefault();try{const name=document.getElementById('name').value.trim(),email=document.getElementById('regEmail').value.trim(),password=document.getElementById('regPassword').value;if(password!==document.getElementById('regConfirm').value)throw new Error('รหัสผ่านไม่ตรงกัน');await registerUser({name,email,password});location.href='login.html';}catch(err){document.getElementById('registerError').textContent=err.message;document.getElementById('registerError').style.display='block';}});});
